//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weathering_with_You_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_sign_in_up
    {
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public string address { get; set; }
    }
}
